"""
Report generator — formats findings into Markdown and JSON reports.

Produces two files:
  - doc-health.md  — Human-readable report for maintainers
  - doc-health.json — Machine-readable report for CI/tooling integration
"""

from __future__ import annotations

import json
import os
from collections import Counter
from datetime import datetime, timezone

from scripts.doc_agent.models import Finding, Severity


def generate_reports(
    findings: list[Finding],
    config: dict,
    output_dir: str,
    dry_run: bool = False,
) -> str:
    """Generate Markdown and JSON reports from findings."""
    md_report = _build_markdown_report(findings, config)
    json_report = _build_json_report(findings, config)

    if dry_run:
        return md_report

    os.makedirs(output_dir, exist_ok=True)

    md_path = os.path.join(output_dir, "doc-health.md")
    json_path = os.path.join(output_dir, "doc-health.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_report)

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_report, f, indent=2, ensure_ascii=False)
        f.write("\n")

    return md_report


def _build_markdown_report(findings: list[Finding], config: dict) -> str:
    """Build the human-readable Markdown report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    severity_counts = Counter(f.severity for f in findings)

    lines: list[str] = []
    lines.append("# 📋 Document Health Report")
    lines.append("")
    lines.append(f"> Generated on **{now}** by the Document Agent.")
    lines.append("")

    # --- Summary ---
    lines.append("## Summary")
    lines.append("")
    total = len(findings)
    crit = severity_counts.get(Severity.CRITICAL, 0)
    warn = severity_counts.get(Severity.WARNING, 0)
    info = severity_counts.get(Severity.INFO, 0)
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total findings | {total} |")
    lines.append(f"| 🔴 Critical | {crit} |")
    lines.append(f"| 🟡 Warning | {warn} |")
    lines.append(f"| 🔵 Info | {info} |")
    lines.append("")

    if not findings:
        lines.append("✅ **No issues found.** Documentation looks healthy!")
        lines.append("")
        return "\n".join(lines)

    # --- Group findings by checker ---
    checker_groups: dict[str, list[Finding]] = {}
    for f in findings:
        checker_groups.setdefault(f.checker, []).append(f)

    checker_labels = {
        "broken_links": "🔗 Broken Links",
        "staleness": "📅 Staleness",
        "todo_scan": "📝 TODO Markers",
        "structure": "🏗️ Structure",
    }

    for checker, group in checker_groups.items():
        label = checker_labels.get(checker, checker)
        lines.append(f"## {label}")
        lines.append("")
        lines.append(f"| Severity | File | Line | Message |")
        lines.append(f"|----------|------|------|---------|")

        # Sort: critical first, then warning, then info
        severity_order = {Severity.CRITICAL: 0, Severity.WARNING: 1, Severity.INFO: 2}
        group.sort(key=lambda f: (severity_order.get(f.severity, 9), f.file, f.line))

        for f in group:
            sev_icon = {
                Severity.CRITICAL: "🔴",
                Severity.WARNING: "🟡",
                Severity.INFO: "🔵",
            }.get(f.severity, "⚪")
            line_str = str(f.line) if f.line > 0 else "—"
            # Escape pipes in the message for Markdown table compatibility
            msg = f.message.replace("|", "\\|")
            lines.append(f"| {sev_icon} {f.severity.value} | `{f.file}` | {line_str} | {msg} |")

        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append("")
    lines.append("_Report generated by [Document Agent](../../scripts/doc_agent/README.md)._")
    lines.append("")

    return "\n".join(lines)


def _build_json_report(findings: list[Finding], config: dict) -> dict:
    """Build the machine-readable JSON report."""
    severity_counts = Counter(f.severity for f in findings)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "total": len(findings),
            "critical": severity_counts.get(Severity.CRITICAL, 0),
            "warning": severity_counts.get(Severity.WARNING, 0),
            "info": severity_counts.get(Severity.INFO, 0),
        },
        "findings": [f.to_dict() for f in findings],
    }
